### PR TITLE
Add linter checks and fix linter warnings

### LINKED ISSUE #36: Add linter inx-faucet

### PR DESCRIPTION
**Pull request by muXxer**

### CODE REVIEW

File: pkg/faucet/faucet.go [hunk 1]
```diff
@@ -74,20 +74,21 @@ type pendingTransaction struct {
...
+type InfoResponse struct {
 	// The bech32 address of the faucet.
 	Address string `json:"address"`
 	// The remaining balance of faucet.
 	Balance uint64 `json:"balance"`
 	// The name of the token of the faucet.
 	TokenName string `json:"tokenName"`
 	// The Bech32 human readable part of the the faucet.
+	//nolint:tagliatelle // false positive
 	Bech32HRP iotago.NetworkPrefix `json:"bech32HRP"`
```
Comment (alexsporn) [inline pkg/faucet/faucet.go]: We actually changed it in the info endpoint, so we should do that here too

**Review by alexsporn — APPROVED** [review]
